name: Cleanup container images

on:
  workflow_run:
    workflows: ["Create and publish container images"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup-untagged:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    permissions:
      packages: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          dry-run: false
          delete-ghost-images: true
          delete-partial-images: true
          delete-orphaned-images: true
          keep-n-untagged: 1
